### ISSUE TITLE
Please reopen #105

### ISSUE THREAD

**Issue by sgreadly** [achillesrasquinha/pipupgrade#117]
#### What's the bug all about?

Hi,

I'm trying to update https://github.com/achillesrasquinha/pipupgrade/issues/105#issuecomment-910801304 but I cannot seem to reach you. 

Also, don't have any means to reopen the issue as I don't have any rights to do so.

Issue still persists. Deleting pip's cache did not resolve the issue.

**Comment by achillesrasquinha** [comment]
Closing this! Issue reopened.
