### ISSUE TITLE
Don't assume "pip" needs to be ran

### ISSUE THREAD

**Issue by slw07g** [achillesrasquinha/pipupgrade#13]
https://github.com/achillesrasquinha/pipupgrade/blob/173ff918cb190306b57a4ade03110e2d04df46a6/src/pipupgrade/_pip.py#L31

Some users have multiple versions of Python installed (and thus multiple versions of pip). Allow a command-line option where users may specify whether they are using pip3 (or even an absolute path to the "pip" they want to run).

**Comment by achillesrasquinha** [comment]
True! I'll send in a fix for this soon.

**Comment by achillesrasquinha** [comment]
Surely using `_pip.main` here is an alternative. Open for discussion!

**Comment by achillesrasquinha** [comment]
I do agree that using the params' is foolish.

**Comment by achillesrasquinha** [comment]
Hi @slw07g 

Has been released for `1.4.0`.
To upgrade `pipupgrade` use `pipupgrade --self`, then you should be able to use `pipupgrade --pip-path PATH_TO_PIP`

**Comment by achillesrasquinha** [comment]
Hi @slw07g, this also seems to enhance #23
