### ISSUE TITLE
Pipupgrade did not update pip prior to updating other packages

### ISSUE THREAD

**Issue by alejandropages** [achillesrasquinha/pipupgrade#20]
I ran pipupgrade today and it updated several packages before updating pip itself. I reran pipupgrade to see if that would have affected the final result and it did have re-update a package. I'm sorry, again I don't have the output.

**Comment by achillesrasquinha** [comment]
@alpacapages I'm not sure I understand. Are you saying it should have updated `pip` at first?

**Comment by achillesrasquinha** [comment]
One thing's being true is that `pipupgrade` should be capable of updating `pip` too!

**Comment by alpacapages** [comment]
I thought pip had to be updated to get access to the latest packages

________________________________

**Comment by alpacapages** [comment]
The reason I'm mentioning it is because I ran it a second time and it had to update another package. I figured that maybe it wasn't aware of that package until after it upgraded pip?

________________________________

**Comment by achillesrasquinha** [comment]
Did you happen to use the `--latest` flag? Im guessing the one you were trying to update was a breaking change (highlights in red). Packages that break changes aren't updated natively unless you specify the mentioned flag.

**Comment by achillesrasquinha** [comment]
This behaviour shouldn't be expected. Internally, `pipupgrade` uses `pip` for updating and updating `pip` prior can potentially break `pipupgrade`.

`pipupgrade` does update `pip` though.

**Comment by achillesrasquinha** [comment]
This has been fixed. #45
