### ISSUE TITLE
The lists do not look right

### ISSUE THREAD

**Issue by wolfembers** [achillesrasquinha/pipupgrade#33]
![Myc6rbC](https://user-images.githubusercontent.com/35852011/60352811-a7bf7f80-9996-11e9-9cd7-f1f36d88334f.png)

I think the preview bit might be a big bugged.

**Comment by achillesrasquinha** [comment]
Windows?

**Comment by wolfembers** [comment]
> Windows?

Yes this is on windows.

**Comment by achillesrasquinha** [comment]
@wolfembers It's fixed with 1.5.2. To upgrade, simply `pipupgrade --self`
