### ISSUE TITLE
'--user' flag and sudo with pipupgrade

### ISSUE THREAD

**Issue by alejandropages** [achillesrasquinha/pipupgrade#4]
I tried to use pipupgrade but got an error saying I was required to use the --user flag due to restricted permissions. 
I tried using sudo, but got an error message saying command was not found with sudo (Obviously some other issue there).

I could not recreate the error but will update if I get it again. In either case it would be cool to be able to add some pip arguments when running pipupgrade.

**Comment by achillesrasquinha** [comment]
Thanks, PR #3 pending.

**Comment by achillesrasquinha** [comment]
This has been fixed and expected to release for `0.3.0`!

**Comment by achillesrasquinha** [comment]
1.0.0 has been released, please upgrade and close if issue doesn't persist.

To upgrade
```
$ pip install --upgrade pipupgrade
```
