### ISSUE TITLE
Add color code scheme in README

### ISSUE THREAD

**Issue by E3V3A** [achillesrasquinha/pipupgrade#66]
There is no explanation of what the different colors mean when you see the list. 
I.e. Yellow, Green, Red, white...

How to update only one "color"??

**Comment by E3V3A** [comment]
@achillesrasquinha 
It's kind of hard to help when we don't know the meaning....

**Comment by achillesrasquinha** [comment]
Hi @E3V3A - Green denotes a patch breaking change, Yellow denotes a minor breaking change and Red denotes a major upgrade as per detected semantic versions of the package (https://semver.org/). 

By default `pipupgrade` doesn't upgrade "red" ones until you add a `--latest` flag. Very similar to how `yarn` does it.

**Comment by achillesrasquinha** [comment]
An enhancement to this would be to upgrade only "desired" ones. In this case `major/minor/patch`

**Comment by achillesrasquinha** [comment]
Released with 1.7.0.

You can use the `--upgrade-type major|minor|patch` to update a specific color. Please check [FAQ](https://github.com/achillesrasquinha/pipupgrade/blob/master/FAQ.md#what-does-each-color-symbolize) for more details.
