### ISSUE TITLE
Flag to ignore certain packages

### ISSUE THREAD

**Issue by MithicSpirit** [achillesrasquinha/pipupgrade#70]
There should be a flag that can be set to ignore certain packages (by name). This would be useful for packages that are not used directly by the user but are instead dependencies that are managed by the system package manager.

**Comment by achillesrasquinha** [comment]
Have you tried - https://github.com/achillesrasquinha/pipupgrade/blob/master/FAQ.md#how-do-i-upgrade-only-selected-packages

**Comment by MithicSpirit** [comment]
I want to do the opposite of that: rather than specifying which packages I want to update I want to specify which one's I _don't_ want to update (while all other packages do get updated). While I could check which packages are outdated, then upgrade the ones that I don't want to be ignored, that would be quite lengthy.

**Comment by achillesrasquinha** [comment]
Seems like a new feature.

**Comment by achillesrasquinha** [comment]
Released with 1.7.2
