### ISSUE TITLE
support virtual environments

### ISSUE THREAD

**Issue by WouterVH** [achillesrasquinha/pipupgrade#73]
Currently the configuration is globally available  for all virtual envs for a specific user:

~/.pipupgrade/config.ini

1) This violates the goal of virtual or isolated environments.
2) This also pollutes the $HOME, 
    modern location should be ~/.config/pipupgrade/ according to XDG_CONFIG_DIRS
   (pip itself also move to ~/.config/pip/)

I propose to support an extra environment-variable:

PIPUPGRADE_CONFIG=<virtualenv-dir>/etc/pipupgrade.ini

**Comment by achillesrasquinha** [comment]
Good call!

**Comment by achillesrasquinha** [comment]
Done!
