### ISSUE TITLE
1.7.4 package.py error adding string to datetime object

### ISSUE THREAD

**Issue by wilcoxon** [achillesrasquinha/pipupgrade#74]
Running pipupgrade 1.7.4 (on Windows 10 with Python 3.8.5 64-bit) gave an error about adding a string to a datetime object.

Here is a patch to fix that issue.

    --- package-1.7.4-bad.py        2020-09-23 16:01:18.981150900 -0500
    +++ package-1.7.4-fix.py        2020-09-23 16:01:30.107120100 -0500
    @@ -110,7 +110,7 @@
                            cache_timeout = settings.get("cache_timeout")
    
                            if res["_updated_at"]:
    -                               time_difference = res["_updated_at"] + timedelta(seconds = cache_timeout)
    +                               time_difference = datetime.strptime(res["_updated_at"], '%Y-%m-%d %H:%M:%S.%f') + timedelta(seconds = cache_timeout)
    
                                    if datetime.now() > time_difference:
                                            sync = True

**Comment by achillesrasquinha** [comment]
Fixed this on develop, pending for release.

**Comment by achillesrasquinha** [comment]
Related to #81
