### ISSUE TITLE
Where is the bootstrap.sql file?

### ISSUE THREAD

**Issue by eabase** [achillesrasquinha/pipupgrade#82]
Looking at this line: 
* https://github.com/achillesrasquinha/pipupgrade/blob/e70314b1457fe03552b9ba06f4a982e712960a7d/src/pipupgrade/db.py#L82

Where is this file?

**Comment by eabase** [comment]
Ha! Crazy Github was not able to find it! 
* https://github.com/achillesrasquinha/pipupgrade/blob/master/src/pipupgrade/data/bootstrap.sql

**Comment by eabase** [comment]
* using `AUTOINCREMENT` should be avoided and is not needed.   
  https://www.sqlite.org/autoinc.html
* using and **`id`** is also not really needed.

**Comment by achillesrasquinha** [comment]
Thanks for the info! I've removed the same.
